{
 "title": "Jemalloc Info",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Snapshot Cache Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Snapshots" }
   ],
   "targets": [
    {
     "expr": "beacon_block_processing_snapshot_cache_size"
    }
   ]
  },
  {
   "title": "Resident",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "jemalloc_bytes_resident" }
   ]
  },
  {
   "title": "Active",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "jemalloc_bytes_active" }
   ]
  },
  {
   "title": "Allocated",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "jemalloc_bytes_allocated" }
   ]
  },
  {
   "title": "Mapped",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "jemalloc_bytes_mapped" }
   ]
  },
  {
   "title": "Retained",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "jemalloc_bytes_retained" }
   ]
  },
  {
   "title": "Metadata",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "jemalloc_bytes_metadata" }
   ]
  },
  {
   "title": "Num Arenas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "Snapshots" }
   ],
   "targets": [
    { "expr": "jemalloc_num_arenas", "legendFormat": "__auto" }
   ]
  }
 ]
}